plugins {
    id 'base'
    id 'net.neoforged.moddev' version '2.0.146' apply false
    id 'net.fabricmc.fabric-loom' version '1.17.20' apply false
}

subprojects {
    apply plugin: 'java-library'
    group = rootProject.mod_group_id
    version = "${rootProject.mod_version}+${rootProject.minecraft_version}"
    base.archivesName = "absmod-${project.name}"
    java {
        toolchain.languageVersion = JavaLanguageVersion.of(25)
        withSourcesJar()
    }
    sourceSets.main.java.srcDir rootProject.file('common/src/main/java')
    sourceSets.main.resources.srcDir rootProject.file('common/src/main/resources')
    tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8' }
    tasks.withType(ProcessResources).configureEach { filteringCharset = 'UTF-8' }
}

tasks.named('build') { dependsOn ':fabric:build', ':neoforge:build' }
